//*****************************************************************************
// Copyright (c) 2014 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
//   Redistribution and use in source and binary forms, with or without
//   modification, are permitted provided that the following conditions
//   are met:
// 
//   Redistributions of source code must retain the above copyright
//   notice, this list of conditions and the following disclaimer.
// 
//   Redistributions in binary form must reproduce the above copyright
//   notice, this list of conditions and the following disclaimer in the
//   documentation and/or other materials provided with the  
//   distribution.
// 
//   Neither the name of Texas Instruments Incorporated nor the names of
//   its contributors may be used to endorse or promote products derived
//   from this software without specific prior written permission.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
// "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
// LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
// OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
// LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
// This file was automatically generated by the Tiva C Series PinMux Utility
// Version: 1.0.4
//
//Some Code Copied and/or Modified from Dr. Xiaorong Zhang for use in SFSU ENGR 478
//All other code written by Rene Siqueiros
//*****************************************************************************

#include <stdint.h>
#include <stdbool.h>
#include <stdlib.h>
#include <math.h>
#include <stdio.h>
#include "inc/hw_types.h"
#include "inc/hw_memmap.h"
#include "inc/hw_gpio.h"
#include "driverlib/sysctl.h"
#include <driverlib/pin_map.h>
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/uart.h"
#include "driverlib/timer.h"
#include "inc/tm4c123gh6pm.h"

//*****************************************************************************

// Global Variables
double timerStart = 0;
double timerStop = 0;

void Timer0A_Handler(void)
{
	TIMER0_ICR_R |= 0x00000001; 
	GPIOPinWrite(GPIO_PORTF_BASE,GPIO_PIN_2,GPIO_PIN_2);
	SysCtlDelay(54);
	GPIOPinWrite(GPIO_PORTF_BASE,GPIO_PIN_2,0x0);
	//timerStart = 0;
	//timerStop = 0;
//	TimerSynchronize(WTIMER0_BASE,WTIMER_0A_SYNC|WTIMER_0B_SYNC);
}

void WTimer0A_Handler(void)
{
	TimerIntClear(WTIMER0_BASE,TIMER_A);
	timerStart = WTIMER0_TAR_R;		
}

void WTimer0B_Handler(void)
{
	TimerIntClear(WTIMER0_BASE,TIMER_B);
	timerStop = WTIMER0_TBR_R;		
}

void Timer0A_Init(void)
{   
	// Change to peripheral lib API?
	volatile uint32_t ui32Loop; 
	
	SYSCTL_RCGC1_R |= SYSCTL_RCGC1_TIMER0; // activate timer0
	ui32Loop = SYSCTL_RCGC1_R;				// Do a dummy read to insert a few cycles after enabling the peripheral.
  TIMER0_CTL_R &= ~0x00000001;     // disable timer0A during setup
  TimerClockSourceSet(TIMER0_BASE, TIMER_CLOCK_PIOSC); //NEW: try setting source to make the timer values make sense
	TIMER0_CFG_R = 0x00000000;       // configure for 32-bit timer mode
  TIMER0_TAMR_R = 0x00000002;      // configure for periodic mode, default down-count settings
  TIMER0_TAILR_R = 0x00186A00;       //NEW: Reload value in hex
	NVIC_PRI4_R &= ~0xC0000000; 	 // configure Timer0A interrupt priority as 2
  NVIC_EN0_R |= 0x00080000;     // enable interrupt 19 in NVIC (Timer0A)
	TIMER0_IMR_R |= 0x00000001;      // arm timeout interrupt
  TIMER0_CTL_R |= 0x00000001;      // enable timer0A
}

void WTimer0_Init(void)
{
	// Wide Timer Init
	SysCtlPeripheralEnable(SYSCTL_PERIPH_WTIMER0);
	TimerDisable(WTIMER0_BASE,TIMER_BOTH);
	TimerConfigure(WTIMER0_BASE, TIMER_CFG_SPLIT_PAIR | TIMER_CFG_A_CAP_TIME | TIMER_CFG_B_CAP_TIME);
	TimerClockSourceSet(WTIMER0_BASE, TIMER_CLOCK_PIOSC);
	TimerControlEvent(WTIMER0_BASE,TIMER_A, TIMER_EVENT_POS_EDGE);
	TimerControlEvent(WTIMER0_BASE,TIMER_B, TIMER_EVENT_NEG_EDGE);
	
	WTIMER0_TAILR_R = 0xFFFFFFFF; //NEW: Try loading in hex
	WTIMER0_TBILR_R = 0xFFFFFFFF;// Old Value : 0x00F42400;
	NVIC_PRI23_R &= ~0xE0E00000; //Set Int Priority to 0 for WT0 A/B (Int# 94, 95)
	TimerEnable(WTIMER0_BASE,TIMER_BOTH);
	TimerIntRegister(WTIMER0_BASE,TIMER_A, WTimer0A_Handler);
	TimerIntRegister(WTIMER0_BASE,TIMER_B, WTimer0B_Handler);
	TimerIntEnable(WTIMER0_BASE, TIMER_CAPA_EVENT);
	TimerIntEnable(WTIMER0_BASE, TIMER_CAPB_EVENT);
	
	// CCP Config
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOC);
  GPIOPinConfigure(GPIO_PC4_WT0CCP0);
  GPIOPinTypeTimer(GPIO_PORTC_BASE, GPIO_PIN_4);
	GPIOPinConfigure(GPIO_PC5_WT0CCP1);
  GPIOPinTypeTimer(GPIO_PORTC_BASE, GPIO_PIN_5);
}

void UART0_Init(void)
{
	// UART for debugging and demo purposes. Might be moved to main C file later
	SysCtlClockSet(SYSCTL_SYSDIV_4 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);
	SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);
  SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);
  GPIOPinConfigure(GPIO_PA0_U0RX);
  GPIOPinConfigure(GPIO_PA1_U0TX);
	UARTFIFOEnable(UART0_BASE);
  GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);	
	UARTConfigSetExpClk(UART0_BASE, SysCtlClockGet(), 115200,(UART_CONFIG_WLEN_8 | UART_CONFIG_STOP_ONE | UART_CONFIG_PAR_NONE));
}

void PortFuncionInit()
{
	// Peripheral Library Brought Back Functionality
	SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOF);
	GPIOPinTypeGPIOOutput(GPIO_PORTF_BASE, GPIO_PIN_2);
	// Not sure if pad config necessary with NPN HW Switch
	GPIOPadConfigSet(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_STRENGTH_12MA, GPIO_PIN_TYPE_STD);
}

int main(void)
{
	// Local Variables
  unsigned int delta = 0;
	char str[4];
	
	// HW Initialization
	SysCtlClockSet(SYSCTL_SYSDIV_4 | SYSCTL_USE_PLL | SYSCTL_OSC_MAIN | SYSCTL_XTAL_16MHZ);
	PortFuncionInit();
	Timer0A_Init();
	WTimer0_Init();
	UART0_Init();
	IntMasterEnable();
	
	
	
		while (1)
	{ // This iteration uses edge interrupt detection on WideTimer 0A/B's CCP. 
		// Timer 0A controls the measurement cycle.
			while((timerStop == 0)||(timerStart == 0))
			{
			}
			delta = (34300*(timerStart - timerStop)/2/16000000);
			sprintf(str, "%3u", delta);
			UARTCharPut(UART0_BASE, str[0]); 
			UARTCharPut(UART0_BASE, str[1]); 
			UARTCharPut(UART0_BASE, str[2]);
			UARTCharPut(UART0_BASE, str[3]);
			UARTCharPut(UART0_BASE, '\n');
			UARTCharPut(UART0_BASE, '\r');
			timerStart = 0;
			timerStop = 0;
		}	
}
